2025-07-17 16:25:45,166 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-17 16:25:45,166 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-17 16:34:45,727 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-17 16:34:45,728 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-17 17:05:16,981 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-17 17:05:16,982 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-17 17:06:12,206 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-17 17:06:12,206 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-17 17:06:41,912 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-17 17:06:41,912 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-17 17:09:59,617 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-17 17:09:59,617 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-17 17:10:48,501 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-17 17:10:48,501 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-17 17:38:21,580 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-17 17:38:21,580 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-17 17:41:11,996 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-17 17:41:11,997 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-17 17:43:27,212 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-17 17:43:27,212 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 09:46:16,339 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 09:46:16,339 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 09:48:33,412 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 09:48:33,413 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 09:52:58,385 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 09:52:58,385 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 09:55:11,434 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 09:55:11,435 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 09:56:24,906 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 09:56:24,906 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 10:00:39,935 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 10:00:39,936 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 10:08:24,261 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 10:08:24,261 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 10:09:02,010 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 10:09:02,010 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 10:11:03,015 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 10:11:03,015 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 10:20:54,816 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 10:20:54,816 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 12:32:28,492 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 12:32:28,493 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 12:40:29,743 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 12:40:29,743 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 12:49:26,801 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 12:49:26,802 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 12:50:28,734 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 12:50:28,734 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 12:55:05,364 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 12:55:05,365 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 12:59:33,126 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 12:59:33,127 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 13:04:05,419 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 13:04:05,419 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 13:06:25,027 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 13:06:25,027 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 15:49:03,929 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 15:49:03,930 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 16:06:22,058 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 16:06:22,058 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 16:33:52,374 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 16:33:52,374 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 16:35:00,230 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 16:35:00,231 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 16:38:33,313 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 16:38:33,314 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 16:45:39,090 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 16:45:39,090 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 16:49:32,412 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 16:49:32,412 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-18 16:51:10,744 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-18 16:51:10,744 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-19 10:45:18,874 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-19 10:45:18,875 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-20 18:19:07,130 - Tests - ERROR - (psycopg2.errors.UndefinedFunction) ПОМИЛКА:  не вдалося визначити оператора рівності для типу json
LINE 2: ...esdetails.short_description AS short_description, gamesdetai...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT DISTINCT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN steambase ON CAST(steambase.appid AS INTEGER) = gamesdetails.steam_appid JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE (categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND steambase.positive - steambase.negative >= %(param_1)s AND gamesdetails.release_data >= %(release_data_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'param_1': 2000, 'release_data_1': datetime.date(2020, 1, 1), 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: ПОМИЛКА:  не вдалося визначити оператора рівності для типу json
LINE 2: ...esdetails.short_description AS short_description, gamesdetai...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 44, in test_news_ganres_to_queue
    news_game_from_ganre(ganre_name=ganre_name)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 51, in news_game_from_ganre
    data = news_service.game_from_ganre(ganre_name=ganre_name,session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 120, in game_from_ganre
    return self.get_game_from_ganre_name_use_case.execute(ganre_name=ganre_name,session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_game_from_ganre_name_use_case.py", line 12, in execute
    data = self.news_repository.get_game_from_ganre_name(ganre_name=ganre_name,session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 80, in get_game_from_ganre_name
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) ПОМИЛКА:  не вдалося визначити оператора рівності для типу json
LINE 2: ...esdetails.short_description AS short_description, gamesdetai...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT DISTINCT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN steambase ON CAST(steambase.appid AS INTEGER) = gamesdetails.steam_appid JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE (categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND steambase.positive - steambase.negative >= %(param_1)s AND gamesdetails.release_data >= %(release_data_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'param_1': 2000, 'release_data_1': datetime.date(2020, 1, 1), 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-07-20 18:19:07,334 - Tests - ERROR - (psycopg2.errors.UndefinedFunction) ПОМИЛКА:  не вдалося визначити оператора рівності для типу json
LINE 2: ...esdetails.short_description AS short_description, gamesdetai...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT DISTINCT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN steambase ON CAST(steambase.appid AS INTEGER) = gamesdetails.steam_appid JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE (categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND steambase.positive - steambase.negative >= %(param_1)s AND gamesdetails.release_data >= %(release_data_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'param_1': 2000, 'release_data_1': datetime.date(2020, 1, 1), 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: ПОМИЛКА:  не вдалося визначити оператора рівності для типу json
LINE 2: ...esdetails.short_description AS short_description, gamesdetai...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 44, in test_news_ganres_to_queue
    news_game_from_ganre(ganre_name=ganre_name)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 51, in news_game_from_ganre
    data = news_service.game_from_ganre(ganre_name=ganre_name,session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 120, in game_from_ganre
    return self.get_game_from_ganre_name_use_case.execute(ganre_name=ganre_name,session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_game_from_ganre_name_use_case.py", line 12, in execute
    data = self.news_repository.get_game_from_ganre_name(ganre_name=ganre_name,session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 80, in get_game_from_ganre_name
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) ПОМИЛКА:  не вдалося визначити оператора рівності для типу json
LINE 2: ...esdetails.short_description AS short_description, gamesdetai...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT DISTINCT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN steambase ON CAST(steambase.appid AS INTEGER) = gamesdetails.steam_appid JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE (categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND steambase.positive - steambase.negative >= %(param_1)s AND gamesdetails.release_data >= %(release_data_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'param_1': 2000, 'release_data_1': datetime.date(2020, 1, 1), 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-07-20 18:19:07,540 - Tests - ERROR - (psycopg2.errors.UndefinedFunction) ПОМИЛКА:  не вдалося визначити оператора рівності для типу json
LINE 2: ...esdetails.short_description AS short_description, gamesdetai...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT DISTINCT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN steambase ON CAST(steambase.appid AS INTEGER) = gamesdetails.steam_appid JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE (categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND steambase.positive - steambase.negative >= %(param_1)s AND gamesdetails.release_data >= %(release_data_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'param_1': 2000, 'release_data_1': datetime.date(2020, 1, 1), 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: ПОМИЛКА:  не вдалося визначити оператора рівності для типу json
LINE 2: ...esdetails.short_description AS short_description, gamesdetai...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 44, in test_news_ganres_to_queue
    news_game_from_ganre(ganre_name=ganre_name)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 51, in news_game_from_ganre
    data = news_service.game_from_ganre(ganre_name=ganre_name,session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 120, in game_from_ganre
    return self.get_game_from_ganre_name_use_case.execute(ganre_name=ganre_name,session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_game_from_ganre_name_use_case.py", line 12, in execute
    data = self.news_repository.get_game_from_ganre_name(ganre_name=ganre_name,session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 80, in get_game_from_ganre_name
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) ПОМИЛКА:  не вдалося визначити оператора рівності для типу json
LINE 2: ...esdetails.short_description AS short_description, gamesdetai...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT DISTINCT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN steambase ON CAST(steambase.appid AS INTEGER) = gamesdetails.steam_appid JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE (categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND steambase.positive - steambase.negative >= %(param_1)s AND gamesdetails.release_data >= %(release_data_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'param_1': 2000, 'release_data_1': datetime.date(2020, 1, 1), 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-07-20 19:08:01,876 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-20 19:08:01,877 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-20 19:25:31,704 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-20 19:25:31,704 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-20 19:49:36,415 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-20 19:49:36,415 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-20 19:50:09,828 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-20 19:50:09,828 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-21 11:40:37,838 - Tests - ERROR - not all arguments converted during string formatting
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 124, in dispathcher
    return self.dispatcher_command[func_name](*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 101, in random_game
    return self.random_game_sync_use_case.execute(session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_sync_random_game.py", line 12, in execute
    data = self.news_repository.random_game_from_price(session=session,limit=1,price=200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 73, in random_game_from_price
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE ((categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND gamesdetails.final_price > %(final_price_1)s AND CAST(gamesdetails.metacritic AS INTEGER)) >= %(param_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'final_price_1': 200, 'param_1': 70, 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 31, in test_news_sender_to_queue
    news_task_creator(type_news=type_news)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 23, in news_task_creator
    data = news_service.dispathcher(func_name=f"{type_news}",session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 128, in dispathcher
    self.logger.error("",e,exc_info=True)
  File "D:\FastAPI\steam_analitics\app\infrastructure\logger\logger.py", line 22, in error
    self.__logger.error(msg,*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 386, in emit
    super().emit(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1168, in emit
    self.handleError(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 139, in format
    return super().format(record)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
2025-07-21 11:51:52,263 - Tests - ERROR - not all arguments converted during string formatting
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 124, in dispathcher
    return self.dispatcher_command[func_name](*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 101, in random_game
    return self.random_game_sync_use_case.execute(session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_sync_random_game.py", line 12, in execute
    data = self.news_repository.random_game_from_price(session=session,limit=1,price=200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 73, in random_game_from_price
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE ((categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND gamesdetails.final_price > %(final_price_1)s AND CAST(gamesdetails.metacritic AS INTEGER)) >= %(param_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'final_price_1': 200, 'param_1': 70, 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 31, in test_news_sender_to_queue
    news_task_creator(type_news=type_news)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 23, in news_task_creator
    data = news_service.dispathcher(func_name=f"{type_news}",session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 128, in dispathcher
    self.logger.error("",e,exc_info=True)
  File "D:\FastAPI\steam_analitics\app\infrastructure\logger\logger.py", line 22, in error
    self.__logger.error(msg,*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 386, in emit
    super().emit(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1168, in emit
    self.handleError(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 139, in format
    return super().format(record)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
2025-07-21 12:02:31,060 - Tests - ERROR - not all arguments converted during string formatting
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 124, in dispathcher
    return self.dispatcher_command[func_name](*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 101, in random_game
    return self.random_game_sync_use_case.execute(session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_sync_random_game.py", line 12, in execute
    data = self.news_repository.random_game_from_price(session=session,limit=1,price=200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 73, in random_game_from_price
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE ((categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND gamesdetails.final_price > %(final_price_1)s AND CAST(gamesdetails.metacritic AS INTEGER)) >= %(param_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'final_price_1': 200, 'param_1': 70, 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 31, in test_news_sender_to_queue
    news_task_creator(type_news=type_news)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 23, in news_task_creator
    data = news_service.dispathcher(func_name=f"{type_news}",session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 128, in dispathcher
    self.logger.error("",e,exc_info=True)
  File "D:\FastAPI\steam_analitics\app\infrastructure\logger\logger.py", line 22, in error
    self.__logger.error(msg,*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 386, in emit
    super().emit(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1168, in emit
    self.handleError(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 139, in format
    return super().format(record)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
2025-07-21 13:18:21,313 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-21 13:18:21,313 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-23 12:56:35,582 - Tests - INFO - {'steam_appid': 76561199054741771, 'user_rating': 4618, 'personaname': 'RAT | Vaznia', 'player_level': 13, 'player_xp': 1759, 'player_xp_needed_to_level_up': 41, 'timecreated': 1588662836, 'timelive': 164601759.58112097, 'friends_count': 12, 'badges_count': 13, 'lastlogoff': 1752683068, 'playtime': 310242, 'allow_games': True, 'allow_friends': True, 'allow_badges': True}
2025-07-23 12:57:31,534 - Tests - CRITICAL - {'detail': 'Steam game not found'}
2025-07-23 12:59:19,149 - Tests - ERROR - not all arguments converted during string formatting
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 124, in dispathcher
    return self.dispatcher_command[func_name](*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 101, in random_game
    return self.random_game_sync_use_case.execute(session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_sync_random_game.py", line 12, in execute
    data = self.news_repository.random_game_from_price(session=session,limit=1,price=200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 73, in random_game_from_price
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE ((categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND gamesdetails.final_price > %(final_price_1)s AND CAST(gamesdetails.metacritic AS INTEGER)) >= %(param_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'final_price_1': 200, 'param_1': 70, 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 31, in test_news_sender_to_queue
    news_task_creator(type_news=type_news)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 23, in news_task_creator
    data = news_service.dispathcher(func_name=f"{type_news}",session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 128, in dispathcher
    self.logger.error("",e,exc_info=True)
  File "D:\FastAPI\steam_analitics\app\infrastructure\logger\logger.py", line 22, in error
    self.__logger.error(msg,*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 386, in emit
    super().emit(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1168, in emit
    self.handleError(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 139, in format
    return super().format(record)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
2025-07-23 12:59:23,180 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-23 12:59:23,181 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-23 14:43:22,612 - Tests - ERROR - not all arguments converted during string formatting
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 124, in dispathcher
    return self.dispatcher_command[func_name](*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 101, in random_game
    return self.random_game_sync_use_case.execute(session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_sync_random_game.py", line 12, in execute
    data = self.news_repository.random_game_from_price(session=session,limit=1,price=200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 73, in random_game_from_price
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE ((categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND gamesdetails.final_price > %(final_price_1)s AND CAST(gamesdetails.metacritic AS INTEGER)) >= %(param_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'final_price_1': 200, 'param_1': 70, 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 31, in test_news_sender_to_queue
    news_task_creator(type_news=type_news)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 23, in news_task_creator
    data = news_service.dispathcher(func_name=f"{type_news}",session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 128, in dispathcher
    self.logger.error("",e,exc_info=True)
  File "D:\FastAPI\steam_analitics\app\infrastructure\logger\logger.py", line 22, in error
    self.__logger.error(msg,*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 386, in emit
    super().emit(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1168, in emit
    self.handleError(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 139, in format
    return super().format(record)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
2025-07-23 14:43:25,443 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-23 14:43:25,443 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-23 14:45:19,347 - Tests - ERROR - not all arguments converted during string formatting
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 124, in dispathcher
    return self.dispatcher_command[func_name](*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 101, in random_game
    return self.random_game_sync_use_case.execute(session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_sync_random_game.py", line 12, in execute
    data = self.news_repository.random_game_from_price(session=session,limit=1,price=200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 73, in random_game_from_price
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE ((categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND gamesdetails.final_price > %(final_price_1)s AND CAST(gamesdetails.metacritic AS INTEGER)) >= %(param_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'final_price_1': 200, 'param_1': 70, 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 31, in test_news_sender_to_queue
    news_task_creator(type_news=type_news)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 23, in news_task_creator
    data = news_service.dispathcher(func_name=f"{type_news}",session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 128, in dispathcher
    self.logger.error("",e,exc_info=True)
  File "D:\FastAPI\steam_analitics\app\infrastructure\logger\logger.py", line 22, in error
    self.__logger.error(msg,*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 386, in emit
    super().emit(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1168, in emit
    self.handleError(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 139, in format
    return super().format(record)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
2025-07-23 14:45:22,359 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-23 14:45:22,359 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-23 14:47:50,933 - Tests - ERROR - not all arguments converted during string formatting
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 124, in dispathcher
    return self.dispatcher_command[func_name](*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 101, in random_game
    return self.random_game_sync_use_case.execute(session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_sync_random_game.py", line 12, in execute
    data = self.news_repository.random_game_from_price(session=session,limit=1,price=200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 73, in random_game_from_price
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE ((categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND gamesdetails.final_price > %(final_price_1)s AND CAST(gamesdetails.metacritic AS INTEGER)) >= %(param_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'final_price_1': 200, 'param_1': 70, 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 31, in test_news_sender_to_queue
    news_task_creator(type_news=type_news)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 23, in news_task_creator
    data = news_service.dispathcher(func_name=f"{type_news}",session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 128, in dispathcher
    self.logger.error("",e,exc_info=True)
  File "D:\FastAPI\steam_analitics\app\infrastructure\logger\logger.py", line 22, in error
    self.__logger.error(msg,*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 386, in emit
    super().emit(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1168, in emit
    self.handleError(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 139, in format
    return super().format(record)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
2025-07-23 14:47:53,647 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-23 14:47:53,647 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-23 14:48:31,079 - Tests - ERROR - not all arguments converted during string formatting
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 124, in dispathcher
    return self.dispatcher_command[func_name](*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 101, in random_game
    return self.random_game_sync_use_case.execute(session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_sync_random_game.py", line 12, in execute
    data = self.news_repository.random_game_from_price(session=session,limit=1,price=200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 73, in random_game_from_price
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE ((categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND gamesdetails.final_price > %(final_price_1)s AND CAST(gamesdetails.metacritic AS INTEGER)) >= %(param_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'final_price_1': 200, 'param_1': 70, 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 31, in test_news_sender_to_queue
    news_task_creator(type_news=type_news)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 23, in news_task_creator
    data = news_service.dispathcher(func_name=f"{type_news}",session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 128, in dispathcher
    self.logger.error("",e,exc_info=True)
  File "D:\FastAPI\steam_analitics\app\infrastructure\logger\logger.py", line 22, in error
    self.__logger.error(msg,*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 386, in emit
    super().emit(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1168, in emit
    self.handleError(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 139, in format
    return super().format(record)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
2025-07-23 14:48:34,231 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-23 14:48:34,231 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-23 15:12:17,627 - Tests - ERROR - not all arguments converted during string formatting
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 124, in dispathcher
    return self.dispatcher_command[func_name](*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 101, in random_game
    return self.random_game_sync_use_case.execute(session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_sync_random_game.py", line 12, in execute
    data = self.news_repository.random_game_from_price(session=session,limit=1,price=200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 73, in random_game_from_price
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE ((categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND gamesdetails.final_price > %(final_price_1)s AND CAST(gamesdetails.metacritic AS INTEGER)) >= %(param_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'final_price_1': 200, 'param_1': 70, 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 31, in test_news_sender_to_queue
    news_task_creator(type_news=type_news)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 23, in news_task_creator
    data = news_service.dispathcher(func_name=f"{type_news}",session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 128, in dispathcher
    self.logger.error("",e,exc_info=True)
  File "D:\FastAPI\steam_analitics\app\infrastructure\logger\logger.py", line 22, in error
    self.__logger.error(msg,*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 386, in emit
    super().emit(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1168, in emit
    self.handleError(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 139, in format
    return super().format(record)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
2025-07-23 15:12:21,097 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-23 15:12:21,097 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-23 15:13:28,556 - Tests - ERROR - not all arguments converted during string formatting
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 124, in dispathcher
    return self.dispatcher_command[func_name](*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 101, in random_game
    return self.random_game_sync_use_case.execute(session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_sync_random_game.py", line 12, in execute
    data = self.news_repository.random_game_from_price(session=session,limit=1,price=200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 73, in random_game_from_price
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE ((categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND gamesdetails.final_price > %(final_price_1)s AND CAST(gamesdetails.metacritic AS INTEGER)) >= %(param_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'final_price_1': 200, 'param_1': 70, 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 31, in test_news_sender_to_queue
    news_task_creator(type_news=type_news)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 23, in news_task_creator
    data = news_service.dispathcher(func_name=f"{type_news}",session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 128, in dispathcher
    self.logger.error("",e,exc_info=True)
  File "D:\FastAPI\steam_analitics\app\infrastructure\logger\logger.py", line 22, in error
    self.__logger.error(msg,*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 386, in emit
    super().emit(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1168, in emit
    self.handleError(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 139, in format
    return super().format(record)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
2025-07-23 15:13:31,824 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-23 15:13:31,824 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-23 15:25:19,493 - Tests - ERROR - not all arguments converted during string formatting
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 124, in dispathcher
    return self.dispatcher_command[func_name](*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 101, in random_game
    return self.random_game_sync_use_case.execute(session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_sync_random_game.py", line 12, in execute
    data = self.news_repository.random_game_from_price(session=session,limit=1,price=200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 73, in random_game_from_price
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE ((categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND gamesdetails.final_price > %(final_price_1)s AND CAST(gamesdetails.metacritic AS INTEGER)) >= %(param_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'final_price_1': 200, 'param_1': 70, 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 31, in test_news_sender_to_queue
    news_task_creator(type_news=type_news)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 23, in news_task_creator
    data = news_service.dispathcher(func_name=f"{type_news}",session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 128, in dispathcher
    self.logger.error("",e,exc_info=True)
  File "D:\FastAPI\steam_analitics\app\infrastructure\logger\logger.py", line 22, in error
    self.__logger.error(msg,*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 386, in emit
    super().emit(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1168, in emit
    self.handleError(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 139, in format
    return super().format(record)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
2025-07-23 15:25:22,620 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-23 15:25:22,621 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-23 15:35:28,570 - Tests - ERROR - not all arguments converted during string formatting
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 124, in dispathcher
    return self.dispatcher_command[func_name](*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 101, in random_game
    return self.random_game_sync_use_case.execute(session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_sync_random_game.py", line 12, in execute
    data = self.news_repository.random_game_from_price(session=session,limit=1,price=200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 73, in random_game_from_price
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE ((categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND gamesdetails.final_price > %(final_price_1)s AND CAST(gamesdetails.metacritic AS INTEGER)) >= %(param_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'final_price_1': 200, 'param_1': 70, 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 31, in test_news_sender_to_queue
    news_task_creator(type_news=type_news)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 23, in news_task_creator
    data = news_service.dispathcher(func_name=f"{type_news}",session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 128, in dispathcher
    self.logger.error("",e,exc_info=True)
  File "D:\FastAPI\steam_analitics\app\infrastructure\logger\logger.py", line 22, in error
    self.__logger.error(msg,*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 386, in emit
    super().emit(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1168, in emit
    self.handleError(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 139, in format
    return super().format(record)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
2025-07-23 15:35:32,496 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-23 15:35:32,496 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-23 15:41:23,231 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-23 15:41:23,231 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-23 15:41:59,229 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-23 15:41:59,230 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-23 15:45:03,767 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-23 15:45:03,767 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-23 15:46:24,239 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-23 15:46:24,239 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
2025-07-23 15:48:41,219 - Tests - ERROR - not all arguments converted during string formatting
Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 124, in dispathcher
    return self.dispatcher_command[func_name](*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 101, in random_game
    return self.random_game_sync_use_case.execute(session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\usecases\news_use_cases\get_sync_random_game.py", line 12, in execute
    data = self.news_repository.random_game_from_price(session=session,limit=1,price=200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\db\sync_repository\news_repository.py", line 73, in random_game_from_price
    result = session.execute(statement)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) ПОМИЛКА:  аргумент конструкції AND повинен бути типу boolean, не типу integer
LINE 4: ...голення')) AND gamesdetails.final_price > 200 AND CAST(games...
                                                             ^

[SQL: SELECT anon_1.steam_appid, anon_1.name, anon_1.is_free, anon_1.short_description, anon_1.requirements, anon_1.initial_price, anon_1.final_price, anon_1.final_formatted_price, anon_1.metacritic, anon_1.discount, anon_1.achievements, anon_1.recomendations, anon_1.img_url, anon_1.trailer_url, anon_1.release_data, anon_1.last_updated, anon_1.random_1, ganres_1.ganres_id, ganres_1.ganres_name, publishers_1.publisher_id, publishers_1.publisher_name, categories_1.category_id, categories_1.category_name 
FROM (SELECT gamesdetails.steam_appid AS steam_appid, gamesdetails.name AS name, gamesdetails.is_free AS is_free, gamesdetails.short_description AS short_description, gamesdetails.requirements AS requirements, gamesdetails.initial_price AS initial_price, gamesdetails.final_price AS final_price, gamesdetails.final_formatted_price AS final_formatted_price, gamesdetails.metacritic AS metacritic, gamesdetails.discount AS discount, gamesdetails.achievements AS achievements, gamesdetails.recomendations AS recomendations, gamesdetails.img_url AS img_url, gamesdetails.trailer_url AS trailer_url, gamesdetails.release_data AS release_data, gamesdetails.last_updated AS last_updated, random() AS random_1 
FROM gamesdetails JOIN ganre_to_many AS ganre_to_many_1 ON gamesdetails.steam_appid = ganre_to_many_1.game_id JOIN ganres AS ganres_2 ON ganres_2.ganres_id = ganre_to_many_1.ganre_id JOIN category_to_many AS category_to_many_1 ON gamesdetails.steam_appid = category_to_many_1.game_id JOIN categories AS categories_2 ON categories_2.category_id = category_to_many_1.category_id 
WHERE ((categories_2.category_name NOT IN (%(category_name_1_1)s)) AND (ganres_2.ganres_name NOT IN (%(ganres_name_1_1)s, %(ganres_name_1_2)s)) AND gamesdetails.final_price > %(final_price_1)s AND CAST(gamesdetails.metacritic AS INTEGER)) >= %(param_1)s ORDER BY random() 
 LIMIT %(param_2)s) AS anon_1 LEFT OUTER JOIN (ganre_to_many AS ganre_to_many_2 JOIN ganres AS ganres_1 ON ganres_1.ganres_id = ganre_to_many_2.ganre_id) ON anon_1.steam_appid = ganre_to_many_2.game_id LEFT OUTER JOIN (publisher_to_many AS publisher_to_many_1 JOIN publishers AS publishers_1 ON publishers_1.publisher_id = publisher_to_many_1.publisher_id) ON anon_1.steam_appid = publisher_to_many_1.game_id LEFT OUTER JOIN (category_to_many AS category_to_many_2 JOIN categories AS categories_1 ON categories_1.category_id = category_to_many_2.category_id) ON anon_1.steam_appid = category_to_many_2.game_id ORDER BY anon_1.random_1]
[parameters: {'final_price_1': 200, 'param_1': 70, 'param_2': 1, 'category_name_1_1': 'Демоверсія гри', 'ganres_name_1_1': 'Сексуальний вміст', 'ganres_name_1_2': 'Оголення'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FastAPI\steam_analitics\tests\test_celery_tasks.py", line 31, in test_news_sender_to_queue
    news_task_creator(type_news=type_news)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\celery\app\task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\infrastructure\celery_app\tasks\news_tasks.py", line 23, in news_task_creator
    data = news_service.dispathcher(func_name=f"{type_news}",session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\application\services\news_service\news_service.py", line 128, in dispathcher
    self.logger.error("",e,exc_info=True)
  File "D:\FastAPI\steam_analitics\app\infrastructure\logger\logger.py", line 22, in error
    self.__logger.error(msg,*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 386, in emit
    super().emit(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1168, in emit
    self.handleError(record)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "D:\FastAPI\steam_analitics\app\.venv\Lib\site-packages\_pytest\logging.py", line 139, in format
    return super().format(record)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
2025-07-23 15:48:44,034 - Tests - INFO - [x] Sent Message subscribe_queue
2025-07-23 15:48:44,034 - Tests - INFO - [x] Sent Message Body = {'type': 'update_steam_games', 'status': True}
